issue#9 - print updated dates
mapbox/missed-issues pull request #10
Opened 2017-11-25 15:59 UTC by mohit2agrawal

2017-11-27 16:27 UTC, mcwhittemore submitted a review, later dismissed
Thanks for this @mohit2agrawal. It's really close. A few small changes and we can merge

2017-11-27 16:27 UTC, mcwhittemore commented on bin/cli.js
> +          if (a.updated_at === b.updated_at)
the name of the variable is `updated`

2017-11-27 16:27 UTC, mcwhittemore commented on bin/cli.js
> +          console.log(`\n**${iss.updated_at}**\n`); // eslint-disable-line no-console
Currently this prints out `undefined` as the variable is `updated` rather than `updated_at`

2017-11-28 05:47 UTC, mohit2agrawal commented
Hi @mcwhittemore, I have made the changes.

2017-11-28 16:42 UTC, mcwhittemore requested changes
Mohit,

Sorry. One more thing. This currently adds date and time rather than just date. This means that most issues will have their own header that looks something like `**2017-09-12T00:59:34Z**`. The linked ticketed requested the date so this should look something like `**2017-09-12**`. This should be considered both with printing and when comparing the last date to the current one.

Thanks,
Matthew

2017-11-29 07:39 UTC, mohit2agrawal commented
Hi @mcwhittemore 
Please check with the changed date.

2017-11-29 21:21 UTC, mcwhittemore approved these changes

2017-11-29 21:21 UTC, merged

2017-11-29 21:21 UTC, mcwhittemore commented
Thanks @mohit2agrawal!